import {defineArrayMember, defineField, defineType} from 'sanity'
import {FLAG_ROUTES, TRIAGE_OUTCOMES} from './constants'

/** One line of a request's checklist: a catalog item and how many units are needed. */
export const needItem = defineType({
  name: 'needItem',
  title: 'Checklist line',
  type: 'object',
  fields: [
    defineField({
      name: 'supplyItem',
      title: 'Supply item',
      type: 'reference',
      to: [{type: 'supplyItem'}],
      options: {filter: 'active != false'},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'quantity',
      type: 'number',
      description: "Units requested. The server caps this at the item's max per household.",
      validation: (rule) => rule.required().integer().min(1).max(50),
    }),
    defineField({
      name: 'pledgedQty',
      title: 'Pledged quantity',
      type: 'number',
      readOnly: true,
      initialValue: 0,
      description:
        'Maintained by the server in the same transaction as each pledge document. Not edited by hand.',
      validation: (rule) => rule.integer().min(0),
    }),
  ],
  validation: (rule) =>
    rule.custom((line: {quantity?: number; pledgedQty?: number} | undefined) =>
      line && typeof line.quantity === 'number' && (line.pledgedQty ?? 0) > line.quantity
        ? 'More units are pledged than requested.'
        : true,
    ),
  preview: {
    select: {
      name: 'supplyItem.name',
      unit: 'supplyItem.unit',
      quantity: 'quantity',
      pledged: 'pledgedQty',
    },
    prepare: ({name, unit, quantity, pledged}) => ({
      title: `${quantity ?? '?'} × ${name ?? 'Unknown item'}`,
      subtitle: [unit, `${pledged ?? 0} pledged`].filter(Boolean).join(' · '),
    }),
  },
})

/** A yes/no concern Jev raised about a request, with its probability. */
export const triageFlag = defineType({
  name: 'triageFlag',
  title: 'Flag',
  type: 'object',
  fields: [
    defineField({name: 'code', type: 'string', validation: (rule) => rule.required()}),
    defineField({name: 'label', type: 'string'}),
    defineField({
      name: 'probability',
      type: 'number',
      description: "Jev's probability (0 to 1) that the flag applies.",
      validation: (rule) => rule.min(0).max(1),
    }),
  ],
  preview: {
    select: {label: 'label', code: 'code', probability: 'probability'},
    prepare: ({label, code, probability}) => ({
      title: label ?? code,
      subtitle: typeof probability === 'number' ? `p = ${probability.toFixed(2)}` : undefined,
    }),
  },
})

/** What triage concluded and why. Written by the server; never typed by hand. */
export const triageSummary = defineType({
  name: 'triageSummary',
  title: 'Triage summary',
  type: 'object',
  readOnly: true,
  fields: [
    defineField({name: 'outcome', type: 'string', options: {list: TRIAGE_OUTCOMES}}),
    defineField({
      name: 'reasons',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      description:
        'Why it went to a human. Composed by code from flags and policy thresholds, never generated by a model.',
    }),
    defineField({name: 'flags', type: 'array', of: [defineArrayMember({type: 'triageFlag'})]}),
    defineField({
      name: 'minConfidence',
      title: 'Lowest answer confidence',
      type: 'number',
      validation: (rule) => rule.min(0).max(1),
    }),
    defineField({
      name: 'decision',
      title: 'Jev decision',
      type: 'reference',
      to: [{type: 'decision'}],
      weak: true,
    }),
    defineField({name: 'decidedAt', type: 'datetime'}),
  ],
})

/** One line of a receipt, after the uploader corrected the OCR output. */
export const receiptLine = defineType({
  name: 'receiptLine',
  title: 'Receipt line',
  type: 'object',
  fields: [
    defineField({name: 'text', type: 'string', validation: (rule) => rule.required()}),
    defineField({
      name: 'amount',
      type: 'number',
      description: 'Price printed on the line, if one was read.',
    }),
    defineField({
      name: 'ocrSimilarity',
      title: 'Similarity to what OCR read',
      type: 'number',
      description:
        'Computed by the server: 1 means the uploader left the line as OCR read it from the photo. Matched lines below the policy threshold go to a verifier.',
      validation: (rule) => rule.min(0).max(1),
    }),
  ],
  preview: {
    select: {text: 'text', amount: 'amount'},
    prepare: ({text, amount}) => ({
      title: text,
      subtitle: typeof amount === 'number' ? `$${amount.toFixed(2)}` : undefined,
    }),
  },
})

/** A receipt line that Jev matched to a checklist line. Code assigns matches; Jev only scores pairs. */
export const proofMatch = defineType({
  name: 'proofMatch',
  title: 'Match',
  type: 'object',
  fields: [
    defineField({
      name: 'lineIndex',
      title: 'Receipt line #',
      type: 'number',
      validation: (rule) => rule.required().integer().min(0),
    }),
    defineField({
      name: 'itemKey',
      title: 'Checklist line key',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'probability',
      type: 'number',
      validation: (rule) => rule.required().min(0).max(1),
    }),
  ],
  preview: {
    select: {lineIndex: 'lineIndex', itemKey: 'itemKey', probability: 'probability'},
    prepare: ({lineIndex, itemKey, probability}) => ({
      title: `Line ${lineIndex} → ${itemKey}`,
      subtitle: typeof probability === 'number' ? `p = ${probability.toFixed(2)}` : undefined,
    }),
  },
})

/** A yes/no question Jev answers about every request (policy-as-content). */
export const flagQuestion = defineType({
  name: 'flagQuestion',
  title: 'Flag question',
  type: 'object',
  fields: [
    defineField({
      name: 'code',
      type: 'string',
      description: 'Stable id used by code and stored on requests (snake_case).',
      validation: (rule) =>
        rule
          .required()
          .regex(/^[a-z][a-z0-9_]*$/, {name: 'snake_case'})
          .max(40),
    }),
    defineField({
      name: 'label',
      type: 'string',
      description: 'Short reason shown to verifiers and requesters.',
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: 'question',
      type: 'text',
      rows: 3,
      description:
        'Sent verbatim to Jev as a yes/no (Noul) question. Refer to the request as `request` (with backticks): that is the name of the field Jev reads.',
      validation: (rule) => rule.required().min(20).max(500),
    }),
    defineField({
      name: 'routesTo',
      title: 'When it fires',
      type: 'string',
      options: {list: FLAG_ROUTES, layout: 'radio'},
      initialValue: 'review',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'threshold',
      title: 'Own threshold (optional)',
      type: 'number',
      description:
        'Fires at or above this probability instead of the global maximum flag probability. Use a lower number where a miss costs more than a false alarm (emergencies).',
      validation: (rule) => rule.min(0).max(1),
    }),
    defineField({name: 'enabled', type: 'boolean', initialValue: true}),
  ],
  preview: {
    select: {label: 'label', code: 'code', enabled: 'enabled', routesTo: 'routesTo'},
    prepare: ({label, code, enabled, routesTo}) => ({
      title: enabled === false ? `${label} (disabled)` : label,
      subtitle: [code, routesTo].filter(Boolean).join(' · '),
    }),
  },
})

function probability(name: string, title: string, description: string) {
  return defineField({
    name,
    title,
    type: 'number',
    description,
    validation: (rule) => rule.required().min(0).max(1),
  })
}

/** Numbers the server gates on. Tuned on real Jev answers, editable without a redeploy. */
export const policyThresholds = defineType({
  name: 'policyThresholds',
  title: 'Thresholds',
  type: 'object',
  fields: [
    probability(
      'catalogMinProbability',
      'Catalog match: minimum probability',
      "A catalog item is proposed for the requester's checklist only at or above this probability, and a number from their words becomes its quantity only at or above it too. The requester edits the checklist either way.",
    ),
    probability(
      'triageMinConfidence',
      'Triage: minimum confidence',
      "Publish automatically only if Jev is at least this confident that the request is in English. Jev's category is shown only at or above it (otherwise a volunteer can set one). Urgency never blocks publishing: it only orders the feed.",
    ),
    probability(
      'maxFlagProbability',
      'Triage: maximum flag probability',
      "Any enabled flag at or above this probability sends the request to a human, unless the flag has its own threshold.",
    ),
    probability(
      'proofMinMatchProbability',
      'Proof: minimum match probability',
      'A receipt line counts as matching a checklist line only at or above this probability.',
    ),
    probability(
      'proofMinCoverage',
      'Proof: minimum coverage',
      'Share of checklist lines that must be matched to a receipt line for automatic verification.',
    ),
    probability(
      'receiptMinProbability',
      'Proof: minimum receipt probability',
      'Minimum probability that the uploaded text is a store receipt at all.',
    ),
    probability(
      'proofMinOcrSimilarity',
      'Proof: minimum similarity to the OCR text',
      "Jev reads text, not the photo. A matched receipt line must be at least this similar to a line OCR read from the photo; lines the uploader rewrote go to a verifier, who compares them with the photo.",
    ),
  ],
})
